const ActionType = {
    INCREMENT: 'INCREMENT',
    DECREMENT: 'DECREMENT',
    OPERATORCLICKED: 'OPERATORCLICKED',
    NUMBERCLICKED: 'NUMBERCLICKED',
    FETCHDATA: 'FETCHDATA',
    FETCHDATASUCCESS: 'FETCHDATASUCCESS'
}

module.exports = ActionType;